#ifndef CBE_H
#define CBE_H

#define err( x ) printf( "Error: " x "\n" );
#define errf( x, ... ) printf( "Error: " x "\n", __VA_ARGS__ );

#define mem_safe( x ) if( !x ) { err( "failed to allocate memory for '" #x "'" ); exit( 1 ); }

const char *program1 = "#define SER 5\n"
		 "#define SRCLK 4\n"
		 "#define RCLK 3\n"
		 "#define WE 2\n"
		 "#define ERASE_VALUE 0xff\n"
		 "void set_dbus_mode( uint8_t pinmode ) {\n"
		 "\tfor( int i = 6; i < 14; i++ ) {\n"
		 "\t\tpinMode( i, pinmode );\n"
		 "\t}\n"
		 "}\n"
		 "void set_dbus_value( uint8_t l_data ) {\n"
		 "\tfor( int i = 13; i > 5; i-- ) {\n"
		 "\t\tdigitalWrite( i, l_data & 1 );\n"
		 "\t\tl_data = l_data >> 1;\n"
		 "\t}\n"
		 "}\n"
		 "void set_address( uint16_t address, bool read ) {\n"
		 "\tdigitalWrite( SRCLK, LOW );\n"
		 "\tshiftOut( SER, SRCLK, MSBFIRST, ( address >> 8 ) | ( read ? 0x00: 0x80 ) );\n"
		 "\tshiftOut( SER, SRCLK, MSBFIRST, address );\n"
		 "\tdigitalWrite( RCLK, LOW );\n"
		 "\tdigitalWrite( RCLK, HIGH );\n"
		 "\tdigitalWrite( RCLK, LOW );\n"
		 "}\n"
		 "void eeprom_write( uint16_t address, uint8_t l_data ) {\n"
		 "\tset_address( address, false );\n"
		 "\tset_dbus_mode( OUTPUT );\n"
		 "\tset_dbus_value( l_data );\n"
		 "\tdigitalWrite( WE, LOW );\n"
		 "\tdelayMicroseconds( 10 );\n"
		 "\tdigitalWrite( WE, HIGH );\n"
		 "\tdelay( 10 );\n"
		 "}\n"
		 "uint8_t eeprom_read( uint16_t address ) {\n"
		 "\tset_address( address, true );\n"
		 "\tset_dbus_mode( INPUT );\n"
		 "\tuint8_t l_data = 0;\n"
		 "\tfor( int i = 6; i < 14; i++ ) {\n"
		 "\t\tl_data = ( l_data << 1 ) + digitalRead( i );\n"
		 "\t}\n"
		 "\treturn l_data;\n"
		 "}\n"
		 "uint8_t data[] = {\n";

const char *program2 = "\n};\n"
		 "void setup( void ) {\n"
		 "\tpinMode( SER, OUTPUT );\n"
		 "\tpinMode( SRCLK, OUTPUT );\n"
		 "\tpinMode( RCLK, OUTPUT );\n"
		 "\tpinMode( WE, OUTPUT );\n"
		 "\tpinMode( LED_BUILTIN, OUTPUT );\n"
		 "\tdigitalWrite( WE, HIGH );\n"
		 "\tSerial.begin( 57600 );\n"
		 "\tSerial.print( \"\" );\n"
		 "\tSerial.print( \"Erasing EEPROM\" );\n"
		 "\tfor( int i = 0; i < 8192; i++ ) {\n"
		 "\t\teeprom_write( i, ERASE_VALUE );\n"
		 "\t\tif( i % 128 == 0 ) Serial.print( \".\" );\n"
		 "\t}\n"
		 "\tSerial.println( \"  done\" );\n"
		 "\tSerial.print( \"Programming EEPROM\" );\n"
		 "\tfor( int i = 0; i < sizeof( data ); i++ ) {\n"
		 "\t\teeprom_write( i, data[ i ] );\n"
		 "\t\tif( i % 128 == 0 ) Serial.print( \".\" );\n"
		 "\t}\n"
		 "\tSerial.println( \"  done\" );\n"
		 "\tSerial.println();\n"
		 "\tSerial.println();\n"
		 "\tSerial.println( \"test\" );\n"
		 "\tfor( int i = 0; i < 8192; i += 32 ) {\n"
		 "\t\tuint8_t l_data[ 32 ];\n"
		 "\t\tfor( int k = 0; k < 32; k++ ) {\n"
		 "\t\t\tl_data[ k ] = eeprom_read( i + k );\n"
		 "\t\t}\n"
		 "\t\tchar buf[ 200 ];\n"
		 "\t\tsprintf( buf, \"\%04x:  \%02x \%02x \%02x \%02x \%02x \%02x \%02x \%02x  \%02x \%02x \%02x\ \%02x \%02x \%02x \%02x \%02x  \%02x \%02x \%02x \%02x \%02x \%02x \%02x \%02x  \%02x \%02x \%02x \%02x \%02x \%02x \%02x \%02x\",\n"
		 "\t\t\ti, l_data[ 0 ], l_data[ 1 ], l_data[ 2 ], l_data[ 3 ], l_data[ 4 ], l_data[ 5 ], l_data[ 6 ], l_data[ 7 ],\n"
		 "\t\t\tl_data[ 8 ], l_data[ 9 ], l_data[ 10 ], l_data[ 11 ], l_data[ 12 ], l_data[ 13 ], l_data[ 14 ], l_data[ 15 ],\n"
		 "\t\t\tl_data[ 16 ], l_data[ 17 ], l_data[ 18 ], l_data[ 19 ], l_data[ 20 ], l_data[ 21 ], l_data[ 22 ], l_data[ 23 ],\n"
		 "\t\t\tl_data[ 24 ], l_data[ 25 ], l_data[ 26 ], l_data[ 27 ], l_data[ 28 ], l_data[ 29 ], l_data[ 30 ], l_data[ 31 ] );\n"
		 "\t\tSerial.println( buf );\n"
		 "\t}\n"
		 "\tSerial.println( \"Done\" );\n"
		 "}\n"
		 "void loop( void ) {\n"
		 "\tstatic bool LED_VAL = true;\n"
		 "\tLED_VAL = !LED_VAL;\n"
		 "\tdigitalWrite( LED_BUILTIN, LED_VAL );\n"
		 "\tdelay( 250 );\n"
		 "}\n";

#endif // CBE_H
